// SPDX-License-Identifier: AGPL-3.0-or-later
// Host runtime for wagasm-ssg (Deno)
// This provides I/O capabilities to the pure WAT SSG

const wasmPath = new URL("../src/wagasm-ssg.wasm", import.meta.url);

// Read the compiled WASM (compile with: wat2wasm wagasm-ssg.wat -o wagasm-ssg.wasm)
const wasmBytes = await Deno.readFile(wasmPath);

// Import functions provided to WASM
const imports = {
  host: {
    write_file: (
      filenamePtr: number,
      filenameLen: number,
      contentPtr: number,
      contentLen: number
    ) => {
      const mem = new Uint8Array(instance.exports.memory.buffer);
      const filename = new TextDecoder().decode(
        mem.slice(filenamePtr, filenamePtr + filenameLen)
      );
      const content = new TextDecoder().decode(
        mem.slice(contentPtr, contentPtr + contentLen)
      );

      Deno.mkdirSync("_site", { recursive: true });
      Deno.writeTextFileSync(`_site/${filename}`, content);
      console.log(`Wrote: _site/${filename}`);
    },

    log: (ptr: number, len: number) => {
      const mem = new Uint8Array(instance.exports.memory.buffer);
      const msg = new TextDecoder().decode(mem.slice(ptr, ptr + len));
      console.log(`[WASM] ${msg}`);
    },
  },
};

// Instantiate the WASM module
const { instance } = await WebAssembly.instantiate(wasmBytes, imports);

// Get exports
const exports = instance.exports as {
  init: () => void;
  set_title: (ptr: number, len: number) => void;
  set_body: (ptr: number, len: number) => void;
  generate_site: () => void;
  memory: WebAssembly.Memory;
};

// Helper to write string to WASM memory
function writeString(str: string, offset: number): number {
  const mem = new Uint8Array(exports.memory.buffer);
  const bytes = new TextEncoder().encode(str);
  mem.set(bytes, offset);
  return bytes.length;
}

// Run the SSG
console.log("wagasm-ssg - Pure WebAssembly SSG");
console.log("================================");

exports.init();

// Set custom title
const titleLen = writeString("My WASM Site", 1024);
exports.set_title(1024, titleLen);

// Set custom body
const bodyLen = writeString("<h1>Hello from Pure WebAssembly!</h1><p>This page was generated by wagasm-ssg, written entirely in WAT.</p>", 2048);
exports.set_body(2048, bodyLen);

// Generate the site
exports.generate_site();

console.log("Done!");
