// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2025 hyperpolymath
// Host runtime for wagasm-ssg (Deno)
// This provides I/O capabilities to the pure WAT SSG

// WebAssembly types
type wasmMemory
type wasmInstance = {exports: {..}}
type wasmModule

// External: WebAssembly.instantiate
@val @scope("WebAssembly")
external instantiate: (
  Js.TypedArray2.Uint8Array.t,
  {..},
) => promise<{"instance": wasmInstance}>  = "instantiate"

// Get WASM file path relative to this module
let wasmPath = %raw(`new URL("../src/wagasm-ssg.wasm", import.meta.url)`)

// Read the compiled WASM
let wasmBytes = Deno.readFileSync(wasmPath)

// Instance holder (set after instantiation)
let instanceRef: ref<option<wasmInstance>> = ref(None)

// Host function: write_file
let writeFile = (filenamePtr: int, filenameLen: int, contentPtr: int, contentLen: int): unit => {
  switch instanceRef.contents {
  | Some(instance) =>
    let mem: Js.TypedArray2.Uint8Array.t = %raw(`new Uint8Array(instance.exports.memory.buffer)`)
    let decoder = %raw(`new TextDecoder()`)

    let filenameSlice: Js.TypedArray2.Uint8Array.t = %raw(`mem.slice(filenamePtr, filenamePtr + filenameLen)`)
    let contentSlice: Js.TypedArray2.Uint8Array.t = %raw(`mem.slice(contentPtr, contentPtr + contentLen)`)

    let filename: string = %raw(`decoder.decode(filenameSlice)`)
    let content: string = %raw(`decoder.decode(contentSlice)`)

    Deno.mkdirSync("_site", {"recursive": true})
    Deno.writeTextFileSync("_site/" ++ filename, content)
    Deno.log("Wrote: _site/" ++ filename)
  | None => Deno.log("Error: instance not initialized")
  }
}

// Host function: log
let logFromWasm = (ptr: int, len: int): unit => {
  switch instanceRef.contents {
  | Some(instance) =>
    let mem: Js.TypedArray2.Uint8Array.t = %raw(`new Uint8Array(instance.exports.memory.buffer)`)
    let decoder = %raw(`new TextDecoder()`)
    let msgSlice: Js.TypedArray2.Uint8Array.t = %raw(`mem.slice(ptr, ptr + len)`)
    let msg: string = %raw(`decoder.decode(msgSlice)`)
    Deno.log("[WASM] " ++ msg)
  | None => Deno.log("[WASM] Error: instance not initialized")
  }
}

// Import object for WASM
let imports = {
  "host": {
    "write_file": writeFile,
    "log": logFromWasm,
  },
}

// Helper to write string to WASM memory
let writeString = (str: string, offset: int, exports: {..}): int => {
  let mem: Js.TypedArray2.Uint8Array.t = %raw(`new Uint8Array(exports.memory.buffer)`)
  let encoder = %raw(`new TextEncoder()`)
  let bytes: Js.TypedArray2.Uint8Array.t = %raw(`encoder.encode(str)`)
  %raw(`mem.set(bytes, offset)`)
  Js.TypedArray2.Uint8Array.length(bytes)
}

// Main entry point
let main = async () => {
  Deno.log("wagasm-ssg - Pure WebAssembly SSG")
  Deno.log("================================")

  // Instantiate the WASM module
  let result = await instantiate(wasmBytes, imports)
  let instance = result["instance"]
  instanceRef := Some(instance)

  let exports = instance.exports

  // Initialize
  %raw(`exports.init()`)

  // Set custom title
  let titleLen = writeString("My WASM Site", 1024, exports)
  %raw(`exports.set_title(1024, titleLen)`)

  // Set custom body
  let bodyLen = writeString(
    "<h1>Hello from Pure WebAssembly!</h1><p>This page was generated by wagasm-ssg, written entirely in WAT.</p>",
    2048,
    exports,
  )
  %raw(`exports.set_body(2048, bodyLen)`)

  // Generate the site
  %raw(`exports.generate_site()`)

  Deno.log("Done!")
}

// Run main
let _ = main()
